### PR TITLE
kaspactl: string slice deser for GetUtxosByAddresses

### PR DESCRIPTION
**Pull request by icook**
Problem:

```bash
./kaspactl -s 172.19.255.200 GetUtxosByAddresses 'kaspa:qzqaex5tzjps7nj77h7hg4sk79asgywy8xnvj8e6ftnuzefx25fd530trcg8a'                                                                                                                                                  16:03:13 1 ↵
error parsing command: Unsupported type 'slice' for parameter 'Addresses'
```

After patch:

```bash
./kaspactl -s 172.19.255.200 GetUtxosByAddresses 'kaspa:qzqaex5tzjps7nj77h7hg4sk79asgywy8xnvj8e6ftnuzefx25fd530trcg8a'                                                                                                                                                      16:11:52 
{
    "getUtxosByAddressesResponse": {
        "entries": [
            {
                "address": "kaspa:qzqaex5tzjps7nj77h7hg4sk79asgywy8xnvj8e6ftnuzefx25fd530trcg8a",
                "outpoint": {
                    "transactionId": "be5c1015d717b814a6822228b5d2c65f2824fb618ddfb725eb2c0d50d40b8d29",
                    "index": 0
                },
                "utxoEntry": {
                    "amount": "100000000",
                    "scriptPublicKey": {
                        "version": 0,
                        "scriptPublicKey": "2081dc9a8b14830f4e5ef5fd745616f17b0411c439a6c91f3a4ae7c165265512daac"
                    },
                    "blockDaaScore": "7775727",
                    "isCoinbase": false
                }
            }
        ],
        "error": null
    }
}
```

With multiple addresses:

```bash
./kaspactl -s 172.19.255.200 GetUtxosByAddresses 'kaspa:qzqaex5tzjps7nj77h7hg4sk79asgywy8xnvj8e6ftnuzefx25fd530trcg8a,kaspa:qr7k3jczjgmay8la2v72u0c6kl5962dq64kq38w0jtx0jhl6j0dpkey0wg5rg'                                                                                  16:11:58 
{
    "getUtxosByAddressesResponse": {
        "entries": [
            {
                "address": "kaspa:qzqaex5tzjps7nj77h7hg4sk79asgywy8xnvj8e6ftnuzefx25fd530trcg8a",
                "outpoint": {
                    "transactionId": "be5c1015d717b814a6822228b5d2c65f2824fb618ddfb725eb2c0d50d40b8d29",
                    "index": 0
                },
                "utxoEntry": {
                    "amount": "100000000",
                    "scriptPublicKey": {
                        "version": 0,
                        "scriptPublicKey": "2081dc9a8b14830f4e5ef5fd745616f17b0411c439a6c91f3a4ae7c165265512daac"
                    },
                    "blockDaaScore": "7775727",
                    "isCoinbase": false
                }
            },
            {
                "address": "kaspa:qr7k3jczjgmay8la2v72u0c6kl5962dq64kq38w0jtx0jhl6j0dpkey0wg5rg",
                "outpoint": {
                    "transactionId": "be5c1015d717b814a6822228b5d2c65f2824fb618ddfb725eb2c0d50d40b8d29",
                    "index": 1
                },
                "utxoEntry": {
                    "amount": "299980000",
                    "scriptPublicKey": {
                        "version": 0,
                        "scriptPublicKey": "20fd68cb029237d21ffd533cae3f1ab7e85d29a0d56c089dcf92ccf95ffa93da1bac"
                    },
                    "blockDaaScore": "7775727",
                    "isCoinbase": false
                }
            }
        ],
        "error": null
    }
}
```

### CODE REVIEW

**Comment by D-Stacks** [comment]
"At least 6 approving reviews are required by reviewers with write access" 

Doesn't this makes it nearly impossible to merge commits from none write access members? as I see it only 4/5 core devs seem to be actively maintaining / commiting the project since december.

**Review by someone235 — APPROVED** [review]
Thank you for the contribution!

**Comment by icook** [comment]
No problem! It looks like the parent tip in the dev branch is failing. Is there any action you'd like me to take to help with the merge?

**Comment by someone235** [comment]
> No problem! It looks like the parent tip in the dev branch is failing. Is there any action you'd like me to take to help with the merge?

The test that failed is a probabilistic test. Looks like it depends on the load on the GitHub servers. Anyway, it passes if you run out locally on your computer

**Pull request merged**
