### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by ey51**
Code of conduct added

### CODE REVIEW

**Comment by ey51** [comment]
A CODE_OF_CONDUCT.md file is needed to get an open source gitbook license.

**Comment by pieroforfora** [comment]
don't!

**Comment by ey51** [comment]
@pieroforfora @someone235  If we want a gitbook free open source license, they require a code of conduct.

**Comment by ey51** [comment]
Updated here https://github.com/kaspanet/kaspad/pull/2183

**Comment by ey51** [comment]
Updated here https://github.com/kaspanet/kaspad/pull/2183

**Pull request closed without merging**
