### PR TITLE
add gh action for build and test

### PR DESCRIPTION
**Pull request by isabellaliu77**
added github action to build and test the project.  The build will run on three platforms ubuntu, mac, windows.

### CODE REVIEW

**Comment by elichai** [comment]
Cool :)
Can you make it run all the tests we currently run? 
you can see them all here: https://github.com/kaspanet/kaspad/blob/v0.8.1-dev/docker/Dockerfile#L23-L33

**Comment by isabellaliu77** [comment]
No problem, I'll work on it now.

**Comment by isabellaliu77** [comment]
Hi, I added all the tests needed, is there anything else I can improve? Thanks.

**Review by elichai — APPROVED** [review]
Thanks!

**Pull request merged**
